// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "gitlab.com/onurcevik/notification-service/internal/domain"

	pgx "github.com/jackc/pgx/v5"
)

// NotificationRepository is an autogenerated mock type for the NotificationRepository type
type NotificationRepository struct {
	mock.Mock
}

// Cancel provides a mock function with given fields: ctx, id
func (_m *NotificationRepository) Cancel(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, tx, n
func (_m *NotificationRepository) Create(ctx context.Context, tx pgx.Tx, n *domain.Notification) error {
	ret := _m.Called(ctx, tx, n)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, *domain.Notification) error); ok {
		r0 = rf(ctx, tx, n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FetchDueScheduled provides a mock function with given fields: ctx
func (_m *NotificationRepository) FetchDueScheduled(ctx context.Context) ([]domain.Notification, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchDueScheduled")
	}

	var r0 []domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Notification, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Notification); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *NotificationRepository) GetByID(ctx context.Context, id string) (*domain.Notification, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Notification, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Notification); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIdempotencyKey provides a mock function with given fields: ctx, key
func (_m *NotificationRepository) GetByIdempotencyKey(ctx context.Context, key string) (*domain.Notification, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetByIdempotencyKey")
	}

	var r0 *domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Notification, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Notification); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByIdempotencyKeyTx provides a mock function with given fields: ctx, tx, key
func (_m *NotificationRepository) GetByIdempotencyKeyTx(ctx context.Context, tx pgx.Tx, key string) (*domain.Notification, error) {
	ret := _m.Called(ctx, tx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetByIdempotencyKeyTx")
	}

	var r0 *domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) (*domain.Notification, error)); ok {
		return rf(ctx, tx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, string) *domain.Notification); ok {
		r0 = rf(ctx, tx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, string) error); ok {
		r1 = rf(ctx, tx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementAttempt provides a mock function with given fields: ctx, id
func (_m *NotificationRepository) IncrementAttempt(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IncrementAttempt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, f
func (_m *NotificationRepository) List(ctx context.Context, f domain.Filter) ([]domain.Notification, string, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Notification
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Filter) ([]domain.Notification, string, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Filter) []domain.Notification); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Filter) string); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.Filter) error); ok {
		r2 = rf(ctx, f)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateStatus provides a mock function with given fields: ctx, id, status, providerMsgID
func (_m *NotificationRepository) UpdateStatus(ctx context.Context, id string, status domain.Status, providerMsgID string) error {
	ret := _m.Called(ctx, id, status, providerMsgID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Status, string) error); ok {
		r0 = rf(ctx, id, status, providerMsgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationRepository creates a new instance of NotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationRepository {
	mock := &NotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
