variables:
  TESTCONTAINERS_RYUK_DISABLED: "true"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

test:
  image: golang:1.25
  stage: test
  services:
    - docker:24-dind
  before_script:
    - go version
  script:
    - go test -v -race -count=1 ./...
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH

lint:
  image: golang:1.25
  stage: test
  before_script:
    - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  script:
    - golangci-lint run --timeout 5m ./...
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH
